// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipLoaderController from "./clip_loader_controller"
application.register("clip-loader", ClipLoaderController)

import GameSearchController from "./game_search_controller"
application.register("game-search", GameSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaginationScrollController from "./pagination_scroll_controller"
application.register("pagination-scroll", PaginationScrollController)

import VideoController from "./video_controller"
application.register("video", VideoController)
