// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TwitchClipsLoaderController from "./twitch_clips_loader_controller"
application.register("twitch-clips-loader", TwitchClipsLoaderController)
