// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipLoaderController from "./clip_loader_controller"
application.register("clip-loader", ClipLoaderController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import GameSearchController from "./game_search_controller"
application.register("game-search", GameSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import PaginationScrollController from "./pagination_scroll_controller"
application.register("pagination-scroll", PaginationScrollController)

import ScrollToTopController from "./scroll_to_top_controller"
application.register("scroll-to-top", ScrollToTopController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import VideoController from "./video_controller"
application.register("video", VideoController)
