# ベースイメージを設定します（Rubyのバージョンを確認）
FROM ruby:3.2.3

# 必要な環境変数を設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要なパッケージのインストール（cronを削除）
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl libvips postgresql-client \
    build-essential git libpq-dev node-gyp pkg-config python-is-python3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Node.jsとYarnのリポジトリの追加
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    NODE_MAJOR=20 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /etc/apt/keyrings/yarn.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update -qq && apt-get install -y nodejs yarn && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# TailwindCSSとesbuildのインストール
RUN npm install -g tailwindcss esbuild

# アプリケーションの設定
RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler

# アプリケーションの依存関係（GemfileとJavaScriptパッケージ）のインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json yarn.lock ./
RUN yarn install

# アプリケーションコードをコピー
COPY . /myapp

# デフォルトのコマンド（開発用にRailsサーバを起動）
CMD ["bash", "-c", "bundle exec rails s -b '0.0.0.0'"]