# fly.toml app configuration file generated for favoriteclipfinder on 2025-09-17T12:39:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'favoriteclipfinder'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]
  dockerfile = './Dockerfile'

[deploy]
  strategy = 'immediate'
  release_command = "bin/rails db:schema:load"

[processes]
  app = 'bin/rails server'
  worker = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
