scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 0 * * *"
      class: FetchTwitchClipsJob
      queue: default
    fetch_japanese_broadcasters_job:
      cron: "30 0 * * *"
      class: FetchJapaneseBroadcastersJob
      queue: default